---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: client
    driver:
      vm_hostname: collectd.commandp.local
      network:
      - ["private_network", {ip: "192.168.10.2"}]
    run_list:
      - recipe[apt]
      - recipe[collectd]
      - recipe[collectd::attribute_driven]
      - recipe[op-collectd]
    attributes:
      collectd:
        influxdb:
          enabled: true
          ipaddress: "192.168.10.3"
          prot: "25826"
        version: "5.4.2"
        checksum: "9778080ee9ee676c7130b1ce86c2843c7359e29b9bd1c1c0e48fcd9cccf089eb"
        url: "https://collectd.org/files/collectd-5.4.2.tar.gz"
        plugins:
          syslog:
            config: { LogLevel: "Info" }
          disk: { }
          swap: { }
          memory: { }
          cpu: { }
          interface:
            config: { Interface: "lo", IgnoreSelected: true }
          df:
            config:
              ReportReserved: false
              FSType: [ "proc", "sysfs", "fusectl", "debugfs", "devtmpfs", "devpts", "tmpfs" ]
              IgnoreSelected: true
  - name: server
    driver:
      vm_hostname: influxdb.commandp.local
      network:
      - ["private_network", {ip: "192.168.10.3"}]
    run_list:
      - recipe[apt]
      - recipe[collectd]
      - recipe[op-influxdb]
      - recipe[collectd::attribute_driven]
      - recipe[grafana]
      - recipe[java]
      - recipe[elasticsearch]
    attributes:
      influxdb:
        config:
          input_plugins:
            collectd:
              enabled: true
              port: 25826
              database: "collectd"
              typesdb: "/opt/collectd/share/collectd/types.db"
      grafana:
        webserver_listen: "192.168.10.3"
        config_cookbook: "op-influxdb"
        window_title_prefix: "commandp - "
        admin_password: "1234"
      collectd:
        version: "5.4.2"
        checksum: "9778080ee9ee676c7130b1ce86c2843c7359e29b9bd1c1c0e48fcd9cccf089eb"
        url: "https://collectd.org/files/collectd-5.4.2.tar.gz"
        plugins:
          syslog:
            config: { LogLevel: "Info" }
          disk: { }
          swap: { }
          memory: { }
          cpu: { }
          interface:
            config: { Interface: "lo", IgnoreSelected: true }
          df:
            config:
              ReportReserved: false
              FSType: [ "proc", "sysfs", "fusectl", "debugfs", "devtmpfs", "devpts", "tmpfs" ]
              IgnoreSelected: true